functionsDirectory = "/root/.openclaw/workspace/gr-spa-vitrine/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []

[build]
publish = "/root/.openclaw/workspace/gr-spa-vitrine"
publishOrigin = "default"
functions = "/root/.openclaw/workspace/gr-spa-vitrine/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/"
to = "/"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog"
to = "/blog"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mentions-legales"
to = "/mentions-legales"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/contact"
to = "/revendeurs"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/notre-histoire"
to = "/a-propos"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nos-revendeurs"
to = "/revendeurs"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/faq"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/les-spas"
to = "/gammes/luxury"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/trouver-votre-spa"
to = "/quiz"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/trouvez-votre-spa-ideal"
to = "/quiz"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/fiches-techniques"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/fiches-commerciales"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/fiches-commerciales-cucina"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/espace-revendeur"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/politique-de-confidentialite"
to = "/politique-confidentialite"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/informations-complementaires"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/les-catalogues"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/notices-dutilisation"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/access-denied"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/checkout"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/connexion"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/log-in"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sign-up"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/user-account"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/parametres-du-compte"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reset-password"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/update-password"
to = "/espace-pro"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/order-confirmation"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/paypal-checkout"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/search"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/le-coin-des-bonnes-affaires"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/la-competition-de-golf-giovanni-riboli-royan"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-ernergy"
to = "/gammes/energy"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-relax"
to = "/gammes/relax"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-therapeutique"
to = "/gammes/luxury"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage"
to = "/gammes/luxury"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spas-de-nage"
to = "/gammes/spa-de-nage"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sauna-hamamm"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/nos-braseros"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-energy/amalfi"
to = "/produits/amalfi"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-energy/bari"
to = "/produits/bari"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-energy/bolzano"
to = "/produits/bolzano"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-energy/capri"
to = "/produits/capri"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-energy/rimini"
to = "/produits/rimini"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage/napoli"
to = "/produits/napoli"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage/napoli-xl"
to = "/produits/napoli-xl"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage/roma"
to = "/gammes/luxury"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage/roma-xl"
to = "/produits/roma-xl"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-massage/torino"
to = "/produits/torino"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-therapeutique/napoli-luxe"
to = "/produits/napoli-luxe"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-therapeutique/roma-luxe"
to = "/produits/roma-luxe"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-therapeutique/torino-luxe"
to = "/produits/torino-luxe"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-therapeutique/signature"
to = "/produits/signature-m"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-relax/le-d-1"
to = "/produits/r1"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-relax/le-d-2"
to = "/produits/r2"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gamme-relax/le-d-3"
to = "/produits/r4"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-de-nage/spa-de-nage-1r3-9"
to = "/produits/swimspa-1r39"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-de-nage/spa-de-nage-1r5-0"
to = "/produits/swimspa-1r50"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-de-nage/spa-de-nage-positano"
to = "/produits/positano"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-de-nage/spa-de-nage-swimspa-2r"
to = "/produits/swimspa-2r"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/braseros/*"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-sur-bordeaux"
to = "/magasins/giovanni-riboli-bordeaux"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-sur-montpellier"
to = "/magasins/giovanni-riboli-montpellier"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/spa-sur-paris"
to = "/revendeurs"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-choisir-son-spa"
to = "/blog/comment-choisir-son-spa"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/les-bienfaits-du-hammam"
to = "/blog/bienfaits-hydrotherapie"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/les-bienfaits-du-sauna"
to = "/blog/bienfaits-hydrotherapie"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/quest-ce-que-la-chromotherapie"
to = "/blog/chromoterapie-couleurs-bien-etre"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/que-choisir-entre-un-spa-et-un-spa-de-nage"
to = "/gammes/spa-de-nage"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/pourquoi-choisir-les-spas-giovanni-riboli"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/quest-ce-que-laromatherapie"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-entretenir-son-spa-au-quotidien"
to = "/blog/entretien-de-votre-spa"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-hiverner-son-spa"
to = "/blog/entretien-de-votre-spa"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-vidanger-son-spa-giovanni-riboli"
to = "/blog/entretien-de-votre-spa"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/la-gamme-energy"
to = "/gammes/energy"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/5-raisons-de-soffir-un-spa"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/barbecue-vs-brasero-les-paris-sont-lances"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-entretenir-son-hammam"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-entretenir-son-sauna"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/comment-utiliser-les-commandes-balboa"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/en-savoir-plus-sur-le-gr-pure"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/foire-expo-de-la-rochelle"
to = "/blog"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/category/*"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/revendeurs/*"
to = "/revendeurs"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/aid-eau-piscine.html"
to = "/magasins/aideau-piscine.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/ge3m.html"
to = "/magasins/ge3m-tout-pour-leau.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/jl-piscines-nogent.html"
to = "/magasins/jl-piscines.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/l-ilot-fleurs.html"
to = "/magasins/lilot-fleurs.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/maison-couleur.html"
to = "/magasins/maison-couleur-couleur-payage.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/o-concept.html"
to = "/magasins/oconcept.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/cuinet-amenagement-exterieur.html"
to = "/magasins/cuinet-amenagement-exterieur-c-piscines.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/sarl-axeldistri.html"
to = "/magasins/sarl-axeldistri-alti-piscines.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/sabiaux-dubrecq.html"
to = "/magasins/maison-bali.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/sabiaux-dubrecq-maison-bali.html"
to = "/magasins/maison-bali.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/ets-coudray.html"
to = "/magasins/bc-piscines-chateaubriant.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/gr-spa-bordeaux.html"
to = "/magasins/giovanni-riboli-bordeaux.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/gr-spa-mauguio.html"
to = "/magasins/giovanni-riboli-montpellier.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/gr-spa-niort.html"
to = "/magasins/giovanni-riboli-niort.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/gr-spa-saint-jory.html"
to = "/magasins/giovanni-riboli-toulouse.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/gr-spa-vaux-sur-mer.html"
to = "/magasins/giovanni-riboli-vaux-sur-mer.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/magasins/riboli-spa-la-rochelle.html"
to = "/magasins/giovanni-riboli-la-rochelle.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]